idf_component_register(
    SRCS 
        "app_main.c"
        "wifi_provisioning.c"
        "mqtt/mqtt_app.c"
        "mqtt/mqtt_connection.c"
        "mqtt/mqtt_publication.c"
        "mqtt/mqtt_subscription.c"
    INCLUDE_DIRS 
        "."
        "mqtt"
    REQUIRES 
        nvs_flash 
        esp_wifi 
        esp_netif 
        wifi_provisioning 
        protocomm 
        json 
        driver
        mqtt
)
